import { describe, expect, it } from "vitest";
import { extractSubtitleTrackUrls, parseSubtitleFile } from "../adapters/subtitleFiles";

describe("subtitle file parsing", () => {
  it("parses WebVTT cues into timed transcript segments", () => {
    const segments = parseSubtitleFile(`WEBVTT

NOTE generated by player

00:00:01.000 --> 00:00:03.500
第一句字幕

00:00:04.000 --> 00:00:06.000 align:start
第二句字幕
第二行
`, "track-file");

    expect(segments).toEqual([
      { startSeconds: 1, endSeconds: 3.5, text: "第一句字幕", source: "track-file" },
      { startSeconds: 4, endSeconds: 6, text: "第二句字幕\n第二行", source: "track-file" },
    ]);
  });

  it("parses SRT cues and ignores numeric cue ids", () => {
    const segments = parseSubtitleFile(`1
00:00:07,200 --> 00:00:09,000
第三句字幕

2
00:01:00,000 --> 00:01:02,250
第四句字幕
`, "track-file");

    expect(segments).toEqual([
      { startSeconds: 7.2, endSeconds: 9, text: "第三句字幕", source: "track-file" },
      { startSeconds: 60, endSeconds: 62.25, text: "第四句字幕", source: "track-file" },
    ]);
  });

  it("extracts subtitle track file urls from html video elements", () => {
    const tracks = [
      { src: "/captions/lesson.vtt", getAttribute: (name: string) => name === "src" ? "/captions/lesson.vtt" : "subtitles" },
      { src: "https://cdn.example.com/lesson.zh.srt", getAttribute: (name: string) => name === "src" ? "https://cdn.example.com/lesson.zh.srt" : "captions" },
      { src: "", getAttribute: (name: string) => name === "src" ? "" : "metadata" },
    ];
    const fakeDocument = {
      querySelectorAll: (selector: string) => selector === "video track[src]" ? tracks : [],
    } as unknown as Document;

    expect(extractSubtitleTrackUrls(fakeDocument, "https://learning.example.com/course/1")).toEqual([
      "https://learning.example.com/captions/lesson.vtt",
      "https://cdn.example.com/lesson.zh.srt",
    ]);
  });
});
